#!/bin/sh

alpha='dd'
background='#2D353B'
selection='#343F44'
comment='#6272a4'

yellow='#DBBC7F'
orange='#E69875'
red='#E67E80'
magenta='#D699B6'
blue='#7FBBB3'
cyan='#83C092'
green='#A7C080'


i3lock \
  --insidever-color=$selection \
  --insidewrong-color=$background \
  --inside-color=$selection \
  --ringver-color=$green \
  --ringwrong-color=$red \
  --ringver-color=$green \
  --ringwrong-color=$red\
  --ring-color=$background \
  --line-uses-ring \
  --keyhl-color=$cyan \
  --bshl-color=$orange \
  --separator-color=$selection \
  --verif-color=$green \
  --wrong-color=$red \
  --layout-color=$blue \
  --date-color=$selection \
  --time-color=$green \
  --screen 1 \
  --blur 17 \
  --clock \
  --indicator \
  --time-str="%I:%M" \
  --verif-text="Checking" \
  --wrong-text="Wrong Input" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --radius=120 \
  --ring-width=16 \
  --pass-media-keys \
  --pass-volume-keys \
  --nofork \
  --show-failed-attempts \
  --image /usr/share/backgrounds/greens.jpg \
  --time-font="JetBrainsMono Nerd Font" \
  --date-font="JetBrainsMono Nerd Font" \
  --layout-font="JetBrainsMono Nerd Font" \
  --verif-font="JetBrainsMono Nerd Font" \
  --wrong-font="JetBrainsMono Nerd Font" \
  \

# eww -c $HOME/.config/eww open greeter
# eww -c $HOME/.config/eww/ close-all && eww -c $HOME/.config/eww/ open profile && sleep 0.8 && eww -c $HOME/.config/eww/ close-all

