#!/usr/bin/env bash

DIR="/home/cleo/.config"

# File
time=`date +%Y-%m-%d-%H-%M-%S`
geometry=`xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="`xdg-user-dir PICTURES`/Screenshots"
file="Screenshot_${time}_${geometry}.png"

# Commands
rofi_cmd="rofi -theme /usr/share/rofi/themes/squared-everforest.rasi"

# Buttons
aliases=" Alias List"
keybinds=" i3 Keybinds"
widgets=" Widgets"
# take shots
aliases () {
  kitty -e --hold ~/scripts/echocustomcmds.sh
}

keybinds () {
  kitty -e --hold ~/scripts/echokeys.sh
}

widgets () {
    kitty -e --hold ~/scripts/echowidgets.sh
}
# Variable passed to rofi
options="$keybinds\n$aliases\n$widgets"

chosen="$(echo -e "$options" | $rofi_cmd -p " Help Menu" -dmenu -selected-row 0 -lines 5 -eh 1 -width 100 -padding 400 -opacity -bw 0 -fullscreen true "85")"
# chosen="$(echo -e "$options" | $rofi_cmd -p 'Select Bookmarks' -dmenu -fullscreen -selected-row 0)"
case $chosen in
    $keybinds)
		keybinds
        ;;
    $aliases)
        aliases
        ;;
    $widgets)
        widgets
        ;;
esac

@theme "/usr/share/rofi/themes/squared-everforest.rasi"
